version: '3.8'
services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    pull_policy: 'always'
    command: '--cluster_mode=emulated'
    ulimits:
      memlock: -1
    ports:
      - "6380:6379"
    volumes:
      - dragonflydata:/data
  rediscluster:
    build: .
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
volumes:
  dragonflydata: